### ISSUE TITLE
Empty data_set directory?

### ISSUE THREAD

**Issue by pkanyuk** [YuanBoot/Intrinsic_Garment_Space#1]
Hi there, I'm interested in giving this technique a try, but it looks like the data_set folder is empty.  Are there more updates we can expect in order to run these examples?

Thanks!
-- Paul

**Comment by YuanBoot** [comment]
@pkanyuk Sorry, I will submit some testing data next week. Please keep your interest and give it a try later. Thanks a lot.

**Comment by pkanyuk** [comment]
Hi @YuanBoot , thanks a ton, I appreciate your willingness to share these examples!

**Comment by YuanBoot** [comment]
Hi @pkanyuk , I have uploaded the data set and updated some scripts for running them easily. If you have any questions, please feel free to contact me.

**Comment by pkanyuk** [comment]
Awesome, thanks so much!  I'll the scripts a try.
